os:
  - osx
  - linux

osx_image: xcode9.2
sudo: required
services:
  - docker

language: cpp

branches:
  only:
    - master
    - stable

env:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36

script:
  ./travis/main.sh
