os: 
  - linux
  - osx

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker

    - os: osx
      osx_image: xcode9.2

install:
  ./travis/install.sh
script:
  ./travis/run.sh
