
language: cpp

branches:
  only:
    - master
    - stable
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MAIN_SCRIPT=./travis/macos.sh

    - os: linux
      sudo: required
      services:
        - docker
      env:
        - MAIN_SCRIPT=./travis/linux.sh

script:
  $MAIN_SCRIPT
