
language: cpp

branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - CONDA_PY=27

    - os: osx
      osx_image: xcode9.2
      env:
        - CONDA_PY=35

    - os: osx
      osx_image: xcode9.2
      env:
        - CONDA_PY=36



    - os: linux
      sudo: required
      services:
        - docker
      env:
        - CONDA_PY=27

    - os: linux
      sudo: required
      services:
        - docker
      env:
        - CONDA_PY=35

    - os: linux
      sudo: required
      services:
        - docker
      env:
        - CONDA_PY=36

script:
  ./travis/main.sh
