
language: cpp

branches:
  only:
    - master
    - stable
matrix:
  include:
    - os: osx
      osx_image: xcode9.2

    - os: linux
      sudo: required
      services:
        - docker

script:
  docker run -it --rm continuumio/miniconda3 /bin/bash -c "./travis/install.sh && ./travis/run.sh"
