os: linux
sudo: required

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  # - "3.5"
  - "3.6"

# matrix:
#    include:
#        - os: osx
#          osx_image: xcode9.2
#          language: python
#          env: CONAN_CURRENT_PAGE=1


install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - miniconda login --username $CONDA_LOGIN_USERNAME --password $CONDA_LOGIN_PASSWORD
script:
  - ./.travis/run.sh
