
# services:
#   - docker
language: cpp

branches:
  only:
    - master
    - stable
matrix:
  include:
    - os: osx
      osx_image: xcode9.2

    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-7-dev
            - gcc-7
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

install:
  ./travis/install.sh
script:
  ./travis/run.sh
