
language: cpp

branches:
  only:
    - master
    - stable
matrix:
  include:
    - os: osx
      osx_image: xcode9.2

    - os: linux
      sudo: required
      services:
        - docker

script:
  docker run -it --rm continuumio/miniconda3 -v "$PWD:/neat" /bin/bash -c "/neat/travis/install.sh && /neat/travis/run.sh"
