os: linux
sudo: required
services:
  - docker

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  # - "3.5"
  - "3.6"

# matrix:
#    include:
#        - os: osx
#          osx_image: xcode9.2
#          language: python
#          env: CONAN_CURRENT_PAGE=1


install:
  ./travis/install.sh
script:
  - conda build conda/
