
language: cpp

branches:
  only:
    - master
    - stable

env:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MAIN_SCRIPT=./travis/macos.sh

    - os: linux
      sudo: required
      services:
        - docker
      env:
        - MAIN_SCRIPT=./travis/linux.sh

script:
  ./travis/main.sh
