os: 
  - linux
  - osx
osx_image: xcode9.2
sudo: required
services:
  - docker
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-6-dev
      - g++-6
      
branches:
  only:
    - master
    - stable

install:
  ./travis/install.sh
script:
  ./travis/run.sh
