
language: cpp

branches:
  only:
    - master
    - stable
matrix:
  include:
    - os: osx
      osx_image: xcode9.2

    - os: linux
      sudo: required
      services:
        - docker

install:
  ./travis/build_docker.sh

script:
  ./travis/run_in_docker.sh
