python:
    - 2.7
    - 3.5
    - 3.6

c_compiler:
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler:
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]

vc:     # [win]
  - 9   # [win]
  - 14  # [win]
  - 14  # [win]

zip_keys:
  -                             # [win]
    - vc                        # [win]
    - c_compiler                # [win]
    - cxx_compiler              # [win]
    - python                    # [win]
    