package:
  name: multineat
  version: 0.5  # Update version in setup.py as well

build:
  number: 
    {{ environ.get('TRAVIS_BUILD_NUMBER', environ.get('APPVEYOR_BUILD_NUMBER', 0)) }}

source:
  path: ..

requirements:
  build:
    - python
    - boost=1.65*
    - py-boost=1.65*
  run:
    - python
    - boost=1.65*
    - py-boost=1.65*
    - numpy>=1.11.3
    - matplotlib=2.2*
    - opencv=3.3*
    # - progressbar # Python 2.7 only, needs to be replaced in main library code

about:
  summary: 
    Portable NeuroEvolution Library http://MultiNEAT.com
